services:
  - type: web
    name: ethiopian-church-website
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATA_DIR
        value: /opt/render/project/src/persistent/data
      - key: UPLOADS_DIR
        value: /opt/render/project/src/persistent/uploads
    disk:
      name: church-persistent-disk
      mountPath: /opt/render/project/src/persistent
      sizeGB: 1
